name: Code style checking
on:
  pull_request:
  push:
    branches: [develop]

jobs:
  prettier:
    name: Prettier checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run prettier-check

      - name: Prettier Output
        if: ${{ failure() }}
        shell: bash
        run: |
          echo "ERROR - Some files are note formated."
          echo "Use 'npm run pretty' to format JS files !"
